### ISSUE TITLE
Work on nightly, not a fork

### ISSUE THREAD

**Issue by alexcrichton** [alexcrichton/futures-await#1]
This library should work at least on nightly Rust! (not require a fork of the compiler). I hope to jot down the major blockers here so we can keep track of this over time. Currently the work items here I believe are.

* [x] Work to get https://github.com/Zoxc/rust/tree/gen upstream. Requires coordinating with the compiler team.
  * [x] [RFC](https://github.com/rust-lang/rfcs/pull/2033)
  * [x] [FCP](https://github.com/rust-lang/rfcs/pull/2033#issuecomment-310135838)
  * [x] Merge RFC
  * [x] [Merge implementation](https://github.com/rust-lang/rust/pull/43076)
* [x] Get https://github.com/rust-lang/rust/pull/40939 landed, verify error messages are as expected.
  * [x] [Implement tokenization in the compiler](https://github.com/rust-lang/rust/issues/43081) - https://github.com/rust-lang/rust/pull/43230

**Comment by alex** [comment]
I believe the second checkbox can be checked now!

**Comment by alexcrichton** [comment]
Excellent! I've updated some points as well

**Comment by alexcrichton** [comment]
Done!

🎉 

(just waiting on a new nightly now)
