### ISSUE TITLE
Very weird borrow checker error

### ISSUE THREAD

**Issue by rubdos** [alexcrichton/futures-await#10]
Hi! Thanks for this cool crate. I just started testing things out, and seems to work as advertised so far, except for this:

I have a type (`MapMessage`) with a method `get_string(&self, &str) -> Result<String>`, which I call in a `#[async]` method. The following works:

```Rust
let a = msg.get_string("abc")?;
Ok(ResultType {
    a = a,
})
```

but

```Rust
Ok(ResultType {
    a = msg.get_string("abc")?,
})
```

Says that `msg` only lives to the last line, and not on line 2.

If you want more context, it is [this method](https://gitlab.com/rubdos/htsp-rs/blob/59b01522f78c894f08de64ef7fb6348ffa3870ce/src/connection/state.rs#L109) which I am trying to rewrite. For now I can use the temporary let bindings, but it'd be nicer to have the getter in the constructor.

**Comment by alexcrichton** [comment]
Thanks for the report! I think this is a [generators bug](https://github.com/rust-lang/rust/issues/44200) so I'm going to close in favor of that report, but be sure to follow that one for updates!

**Comment by rubdos** [comment]
> sure to follow that one for updates!

Thanks! Following :-)

**Comment by rubdos** [comment]
Should be fixed by https://github.com/rust-lang/rust/pull/44392
