### ISSUE TITLE
Lacking solution for associated types

### ISSUE THREAD

**Issue by alex** [alexcrichton/futures-await#14]
This shows up when implementing `hyper::server::Service`. Consider the following code

```rust
impl hyper::server::Service for HttpHandler {
    type Request = hyper::server::Request;
    type Response = hyper::server::Response;
    type Error = hyper::Error;
    type Future = ... // What goes here!

    fn call(&self, request: hyper::server::Request) -> Self::Future {
        async_block! { }
    }
}
```

You can't use `impl Future` here, like you can with a method. And you can't name the type, because `futures::__rt::GenFuture` isn't `pub`. _A_ solution that works is to make `type Future = Box<Future<Item = Self::Response, Error = Self::Error>>;`, and wrap `async_block! { }` with `Box::new()`. But this has the downside that you can't specify a lifetime on it (or maybe I'm doing everything wrong), also it's an extra allocation (if you care about such things).

**Comment by alexcrichton** [comment]
Yeah this is a case where I believe `impl Trait` won't work just yet (but maybe will one day?) For now I'd recomend boxing.

**Comment by alex** [comment]
I suspect as much.

This should probably be considered a documentation issue then.

**Comment by alexcrichton** [comment]
Mind adding a few sentences to the [existing caveats for traits](https://github.com/alexcrichton/futures-await#futures-in-traits)?
