### ISSUE TITLE
More missing spans for async_block

### ISSUE THREAD

**Issue by alex** [alexcrichton/futures-await#26]
I seem to find all the ways to make things fail :-)

The code in question is at: https://github.com/alex/ct-tools/compare/tokio-async#diff-1802a8ee491d4312703790b7b22f29ceR101

And the error message is:

```
error[E0507]: cannot move out of captured outer variable in an `FnMut` closure
  --> <proc-macro source code>:1:1
   |
1  | move
   | ^^ cannot move out of captured outer variable in an `FnMut` closure
   |
  ::: src/ct.rs
   |
97 |     let payload = serde_json::to_vec(&AddChainRequest {
   |         ------- captured outer variable

error: aborting due to previous error

error: Could not compile `ct-tools`.
```

**Comment by alexcrichton** [comment]
Hm now so *this* may be a "bug" in rustc or a place where rustc could improve, unfortunately there's no real span here to use to attach to what we generate.

Otherwise I'm not actually sure how to fix this...

**Comment by alex** [comment]
👍 -- is this something you're able to turn into an upstream bug; unfortunately I don't know my way around proc macros nearly well enough to file it coherently unfortunately.

**Comment by alexcrichton** [comment]
Yeah I'll look into formulating something

**Comment by alexcrichton** [comment]
Ok turns out I couldn't ever minimize it to a reportable issue, and ended up fixing it regardless!
