### ISSUE TITLE
Is it deliberately not on crates.io?

### ISSUE THREAD

**Issue by vi** [alexcrichton/futures-await#27]
I tried and it works (I do `.map_err(|_|())` error handling although). Why is it not on crates.io? Specifically to avoid dependencies?

I expect even half-working futures-await on creates.io can bring various usages of coroutines into more discoverable space, for better basis for further discussion about the feature.

**Comment by alexcrichton** [comment]
Nah right now the main reason is that its dependencies, namely `syn`, are not on crates.io

**Comment by vi** [comment]
Both [syn](https://crates.io/crates/syn) and [quote](https://crates.io/crates/quote) seem to be on crates.io. Or is it a wrong `syn`?

**Comment by alexcrichton** [comment]
Indeed they are! They are not the versions on the master branches, though. You can test by switching the dependencies to crates.io :)

**Comment by vi** [comment]
If I force usage of crate.io's versions of syn, quote and proc-macro2 on futures-async-macro, it fails with numerous missing content like `syn::tokens`.

So I expect `futures-await` to be on track to publishing on crates.io, blocked only by dependencies.

**Comment by alexcrichton** [comment]
I'm going to close this for now as we're still waiting on publication of syn/etc to publish this crate.
