### ISSUE TITLE
Attribute panic when result contains type from macro parameter

### ISSUE THREAD

**Issue by vorner** [alexcrichton/futures-await#29]
I wanted to generate a bunch of async functions that looked very similar. But I discovered that whenever the return type contains a macro parameter, the async custom attribute panics. For example, this code:

```rust
#![feature(conservative_impl_trait, generators, proc_macro)]
extern crate futures_await as futures;

use futures::prelude::*;

macro_rules! xyz {
    ($t: ty) => {
        #[async]
        fn crash() -> Result<$t, ()> {
            if true {
                let x: $t = Default::default();
                Ok(x)
            } else {
                Err(())
            }
        }
    };
}

xyz!(u32);

fn main() {
    println!("Hello, world!");
}
```

gives the output:

```
error: custom attribute panicked
  --> src/main.rs:8:9
   |
8  |         #[async]
   |         ^^^^^^^^
...
20 | xyz!(u32);
   | ---------- in this macro invocation
   |
   = help: message: unknown delimiter:  

error: Could not compile `crash`.
```

When I replace the `$t`s in the macro with `u32` directly, it compiles.

However, I don't see how this can even be possible. Shouldn't the `xyz` macro be fully expanded first and then the result passed to the `async` proc macro? Therefore, shouldn't the proc macro get the same input in both cases?

I understand this might be an unimportant issues with an experimental crate like this and may be closed as won'tfix (and I'm not really sure the problem comes from this crate and not from something below it), but I wanted to make sure it is at least known.

**Comment by alexcrichton** [comment]
Thanks for the report! I believe https://github.com/dtolnay/quote/pull/47 should fix this
