### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by cramertj** [alexcrichton/futures-await#37]
I'd really like to do some more in-depth experimentation with futures-await, but unfortunately the system I'm working in doesn't support git dependencies. I understand that publishing futures-await is currently blocked on publishing new versions of syn, quote, and synom. @alexcrichton suggested a possible workaround for this: we could publish forks (e.g. "alexcrichton-syn") to crates.io and use those crates instead (temporarily).

cc @mystor -- what do you think about this plan?

**Comment by alexcrichton** [comment]
cc @mystor

**Comment by alexcrichton** [comment]
Ok @mystor and I talked in person and I've published on crates.io now! The syn/quote crates are temporarily published under `futures-await-syn` and `futures-await-quote`

**Comment by cramertj** [comment]
Awesome! Thanks.
