### ISSUE TITLE
Typo in README 

### ISSUE THREAD

**Issue by hcpl** [alexcrichton/futures-await#38]
The README [mentions `three pieces` while listing only two](https://github.com/alexcrichton/futures-await/blame/fae6a1af075f5252c73a167e53891a2f9655ed6d/README.md#L532). The third point was removed in https://github.com/alexcrichton/futures-await/commit/a0e10c5528c4c3b9c45da12bb7111fcfd962c4a3#diff-04c6e90faac2675aa89e2176d2eec7d8L488.

Not sure if this is intended, so I'm issuing this instead of PR`ing.

https://github.com/alexcrichton/futures-await/blame/fae6a1af075f5252c73a167e53891a2f9655ed6d/README.md#L532

**Comment by alexcrichton** [comment]
Ah yeah I think that should just be "two" now, so feel free to send a PR!

**Comment by hcpl** [comment]
Thanks! PR is incoming now.
