### ISSUE TITLE
Support multiple async_block! returns

### ISSUE THREAD

**Issue by thisismiller** [alexcrichton/futures-await#48]
Trying to build a function of the form

```
fn DoSomething() -> impl Future<Item=(), Error=Error> {
  match Some(1) {
    Some(x) => async_block! { Ok(()) }
    None => async_block! { Ok(()) }
  }
}
```

Fails with an error that looks like:

```
error[E0308]: match arms have incompatible types
  --> src/main.rs:38:5
   |
38 | /     match Some(1) {
39 | |         Some(x) => { async_block! { Ok(()) } }
40 | |         None => { async_block! { Ok(()) } }
41 | |     }
   | |_____^ expected generator, found a different generator
   |
   = note: expected type `impl futures::__rt::MyFuture<<[generator@src/main.rs:39:22: 39:45 _] as futures::__rt::Generator>::Return>`
              found type `impl futures::__rt::MyFuture<<[generator@src/main.rs:40:19: 40:42 _] as futures::__rt::Generator>::Return>`
note: match arm with an incompatible type
  --> src/main.rs:40:17
   |
40 |         None => { async_block! { Ok(()) } }
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I was using this (when matching against an enum representing the RPCs a server could handle) to pick everything off of `self` that I needed, and then wrap the heavy lifting in an `async_block!`... but it appears I can't?  (A similar error occurs if one instead moves the two `async_block!`s into their own `#[async]` functions, and call them instead.)

**Comment by alexcrichton** [comment]
Thanks for the report! This is a result of closures and generator and such in Rust though which have unique types. To do something like this you'll want to return boxed futures or something like `Either` in the futures crate.
