### ISSUE TITLE
Consder add `Result: 'lifetime` in generics for async functions

### ISSUE THREAD

**Issue by andreytkachenko** [alexcrichton/futures-await#53]
lifetimes are not supported now AFAIK

Here is my proposals:

Good looking, but non working version:
```rust
#[async]
fn func<'a>(val: &'a data) -> Result<(), ()> + 'a {
    ...
}
```
Working version 1:
```rust
#[async]
fn func<'a>(val: &'a data) -> impl Result<(), ()> + 'a {
    ...
}
```
Working version 2:
```rust
#[async]
fn func<'a, Result: 'a>(val: &'a data) -> Result<(), ()> {
    ...
}
```

**Comment by alexcrichton** [comment]
Thanks for the report! I'd also love to get this working but I think we'll want to see how impl Trait plays out on stable. I'd prefer to not have any special syntax for async/await and instead only use normal Rust syntax/elision for these cases.

**Comment by andreytkachenko** [comment]
I agree with you that we should keep close to native Rust's syntax, as much as possible. But since the return type actually not impl Future<..> it is impossible to add lifetime parameter and hence pass by reference anything ('static not counting). But I am suggesting to have something what can be useful (even temporary until impl Trait become stable). I have made _magic_ `'f` lifetime in my fork. Maybe it will be usefull for somebody.

**Comment by andreytkachenko** [comment]
Here is the commit https://github.com/andreytkachenko/futures-await/commit/84fe483d1b8e6e66f335de0e58d23e7bc800cc3b

**Comment by withoutboats** [comment]
The return type now captures all lifetimes, making this change unnecessary. :)
