### ISSUE TITLE
Consider adding `stream_next` or similar macro 

### ISSUE THREAD

**Issue by andreytkachenko** [alexcrichton/futures-await#54]
The idea is exactly the same as a regular `await!` macro, but related to streams. 
This macro may be helpful when you need await an item from stream (when processing stream in item-by-item fashion). Here is my version of such macro (rewrote version of original await macro):
```rust
#[macro_export]
macro_rules! stream_next {
    ($e:expr) => ({
        loop {
            match ::futures::Stream::poll(&mut $e) {
                ::futures::__rt::core::result::Result::Ok(::futures::Async::Ready(e)) => {
                    break ::futures::__rt::core::result::Result::Ok(e)
                }
                ::futures::__rt::core::result::Result::Ok(::futures::Async::NotReady) => {}
                ::futures::__rt::core::result::Result::Err(e) => {
                    break ::futures::__rt::core::result::Result::Err(e)
                }
            }

            yield ::futures::Async::NotReady
        }
    })
}
```

**Comment by alexcrichton** [comment]
Seems reasonable to me! Perhaps something like `await_stream` or `await_stream_next` though to make it clear that it's blocking?

**Comment by awestlake87** [comment]
I agree that this can be useful, but this can be done relatively easily using regular futures. I don't think there needs to be a macro for it. here's an [example](https://play.rust-lang.org/?gist=0bc8bac33cc3ea93da39061b69909905&version=undefined)

here's what it might look like with `await!`

```rust
let next = await!(stream.and_then(|item| Ok(item))
    .into_future()
    .map(|item| item.unwrap())
)?;
```

**Comment by awestlake87** [comment]
or [more generally](https://play.rust-lang.org/?gist=fda23dab18aba20d960c23cea17215f3&version=nightly) where the `await!` would look something like this:

```rust
if let (Some(next), stream) = await!(stream_next(stream).map_err(|(e, _)| e))? {
    // do something with 'next'
}
```

**Comment by alexcrichton** [comment]
@awestlake87 it's true yeah that `into_future` can be used but I'd imagine that for a number of usages the consumption behavior of the stream can be annoying and/or difficult to work around

**Comment by awestlake87** [comment]
I see what you mean @alexcrichton. If borrows are out of the question for async functions, then a macro is the only thing that'll allow you to do that without temporarily taking ownership of the stream.

**Comment by kdy1** [comment]
What about await_item!()?
As name `item` is used in `Iterator`, I don't think it will be confused with `Future::Item`. (Stream is an asynchronous version of Iterator)

**Comment by alexcrichton** [comment]
Sounds like a good name to me!

**Comment by andreytkachenko** [comment]
Since it was merged we can close the issue
