### ISSUE TITLE
Impossibility to use await (in fact "yield") inside iterator adapters (in fact "closures")

### ISSUE THREAD

**Issue by PaulGrandperrin** [alexcrichton/futures-await#56]
Hi, as shown in the example below, it is currently impossible to use `await` (in fact `yield`) inside iterator adapters (in fact "closures").

When one knows how the async/await macros are implemented (with syntactically closure-looking generators), the compile-time error makes sense, but **I think there are two problems** with the current situation:
  - A minor problem is that **the error message doesn't make sense** to someone who doesn't know the implementation details of async/await. I think it's not a big deal because it's an experimental feature and it's probably very difficult to solve without proper compiler support anyway.
  - A major problem and more long-term issue is that this **clashes with one of the defining aspects of Rust**: functional features, namely, closures and iterator adapters.
I don't know the story of others languages with both iterator adapters and async/await constructs like Scala but I'm hopeful that Rust's async/await story is still early-stage enough so that there is still a path toward implementing async constructs that works with closures and iterator adapters.

Example of code featuring iterator adapters and closure that **doesn't** compile:
```rust
#![feature(proc_macro, conservative_impl_trait, generators)]
extern crate futures_await as futures;
use futures::prelude::*;

#[async]
fn get_future_squared(i: u64) -> Result<u64, ()> {
    Ok(i*i)
}

#[async]
fn get_future_sum_squared() -> Result<i64, ()> {
    let s = (0..10).map(|i|{ // error[E0628]: generators cannot have explicit arguments
      await!(get_future_squared(i)).unwrap()
    }).sum();
    Ok(s)
}

fn main() {
  println!("{:?}", get_future_sum_squared().poll());
}
```

**Comment by PaulGrandperrin** [comment]
I guess, in a way, it's kind of the same issue as not being able to use `try!` or `?` in an iterator adapter.

**Comment by alexcrichton** [comment]
Thanks for the report! This isn't really something this crate can resolve, however, it's more of a philosophical issue of sorts in the sense that this is the "viral" nature of async/await where it can't necessarily be used in arbitrary locations. The way to do this, for example, would be to use streams rather than iterators.

**Comment by PaulGrandperrin** [comment]
It's clearly a kind of meta-issue but I think it would be useful to have a place to speak about the associated tradeoffs and implications.
Would [rust-lang/rfcs](https://github.com/rust-lang/rfcs) be a good place for that?

**Comment by alexcrichton** [comment]
I think internals.rust-lang.org would probably be the best location

**Comment by PaulGrandperrin** [comment]
Ok got it.

**Comment by alexcrichton** [comment]
Ok! In that case I'll close this
