### ISSUE TITLE
Inscrutable error messages 

### ISSUE THREAD

**Issue by alex** [alexcrichton/futures-await#6]
Hopefully this is the right place to file this. I'm attempting to use futures-await (WHICH I AM SO EXCITED ABOUT) but unfortunately hitting some error messages which I'm totally unable to parse.

All of this code is at: https://github.com/alex/ct-tools/compare/tokio-async (8d5cb39 at the time of this comment). Here's the relevant bits of the error:

```
error[E0477]: the type `impl futures::Future` does not fulfill the required lifetime
 --> <proc-macro source code>:1:1
  |
1 | impl
  | ^
  |
  = note: type must satisfy the static lifetime

error[E0495]: cannot infer an appropriate lifetime due to conflicting requirements
  --> src/google.rs:30:1
   |
30 | #[async]
   | ^^^^^^^^
   |
note: first, the lifetime cannot outlive the anonymous lifetime #1 defined on the function body at 30:8...
  --> src/google.rs:30:8
   |
30 |   #[async]
   |  ________^
31 | | pub fn fetch_trusted_ct_logs<C: hyper::client::Connect>(
   | |___^
note: ...so that expression is assignable (expected &hyper::Client<C>, found &hyper::Client<C>)
  --> src/google.rs:30:1
   |
30 | #[async]
   | ^^^^^^^^
   = note: but, the lifetime must be valid for the static lifetime...
note: ...so that the type `impl futures::Future` will meet its required lifetime bounds
  --> <proc-macro source code>:1:1
   |
1  | impl
   | ^

error[E0564]: only named lifetimes are allowed in `impl Trait`, but `` was found in the type `impl futures::Future`
 --> <proc-macro source code>:1:1
  |
1 | impl
  | ^

```

(Probably worth mentioning that this is porting some sync code to be async, and I was definitely hoping for the compiler to guide me!)

**Comment by rozaliev** [comment]
@alex I guess async macro doesn't preserve original source code info yet. Meantime https://github.com/dtolnay/cargo-expand should help you with debug.

**Comment by alexcrichton** [comment]
Thanks for the report! Using unstable procedural macros definitely gives us the ability to specify spans on all tokens we hand back to the compiler, so we probably just need to munge a few more tokens here I think.

**Comment by alex** [comment]
@alexcrichton That sounds good -- FWIW another case that has poor error messages is if you mark a functin `#[async]` but don't return a `Result`.

**Comment by alexcrichton** [comment]
Ok as shown in https://github.com/alexcrichton/futures-await/commit/383c1bcd17b497898b0c115f7c529ed79fb135b4 I believe this was fixed by https://github.com/alexcrichton/futures-await/commit/2f7a92116abc82c5c504fca0ce737b032064ee81, so closing.
