### ISSUE TITLE
unsafe allowed inside `#[async]` functions

### ISSUE THREAD

**Issue by Nemo157** [alexcrichton/futures-await#74]
As an example, running this will segfault without any warnings: 

```rust
#![feature(proc_macro, conservative_impl_trait, generators)]

extern crate futures_await as futures;

use futures::prelude::async;

#[async]
fn glass() -> Result<u32, futures::Never> {
    Ok(*(::std::ptr::null() as *const u32))
}

fn main() {
    futures::stable::block_on_stable(glass()).unwrap();
}

```

while the same example with `s/async/async_move/` will fail to compile:

```
error[E0133]: dereference of raw pointer requires unsafe function or block
 --> examples/safety.rs:9:8
  |
9 |     Ok(*(::std::ptr::null() as *const u32))
  |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ dereference of raw pointer
```

This appears to be caused by [this unhygenic `unsafe` block](https://github.com/alexcrichton/futures-await/blob/3983f563fe61b76b655fa15645467aa545c0dfb5/futures-await-async-macro/src/lib.rs#L209), I assume this has something to do with self-referential generators, but I'm hoping there's some way to fix this to avoid accidental unsafety.

**Comment by withoutboats** [comment]
Ugh this is quite problematic! Once Pin stuff lands, we can make changes to generators so that this unsafe block should be going away, but until then... cc @cramertj

**Comment by Arnavion** [comment]
Please backport this to 0.1.x while 0.2.x is still alpha.

```
   Compiling futures-await v0.1.0
error[E0133]: call to unsafe function requires unsafe function or block
   --> C:\Users\Arnavion\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-await-0.1.0\src\lib.rs:123:19
    |
123 |             match self.0.resume() {
    |                   ^^^^^^^^^^^^^^^ call to unsafe function

error[E0133]: call to unsafe function requires unsafe function or block
   --> C:\Users\Arnavion\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-await-0.1.0\src\lib.rs:143:19
    |
143 |             match self.gen.resume() {
    |                   ^^^^^^^^^^^^^^^^^ call to unsafe function
```

**Comment by Nemo157** [comment]
See #79, this is actually about the inverse problem where you could use unsafe functions without adding an `unsafe` block to your code.
