### ISSUE TITLE
#[async(boxed)] does not work in 0.2

### ISSUE THREAD

**Issue by shisoft** [alexcrichton/futures-await#85]
I think it is time to move on to 0.2 but after 0.2 introduced pinned, it seems like lost box arg. 

> the #[async] attribute currently only takes `pinned` `pinned_send` as an arg

Will box to be implemented in the future? If not, how can I cope with impl trait functions? I used to be wrap future trait type with in `Box` as return type.

p.s if anyone can explain what are those 2 new attributes that will be nice. 

Thank you.

**Comment by Nemo157** [comment]
See https://github.com/rust-lang-nursery/futures-rs/issues/918

I think at this point I would recommend waiting on the next `futures` 0.2 pre-release. That should include `async`/`await` directly and I'm going to attempt to make sure the arguments are made consistent and documented before then.

**Comment by shisoft** [comment]
I agreed, the branch looks unstable and lacks documentation
