### ISSUE TITLE
Minor Issue With proc_macro2

### ISSUE THREAD

**Issue by SeunLanLege** [alexcrichton/futures-await#90]
tracking issue here alexcrichton/proc-macro2#78 

this crate uses `proc_macro2::Span::def_site` but it is only re-expoted from the proc_macro crate from proc_macro2 except the enviroment variable  RUSTFLAGS='--cfg procmacro2_semver_exempt' is set  

There has to be way to configure the how rustc builds this crate such that upstream crates that depend on this one don't have to set the `RUSTFLAGS` variable. help is welcome.

**Comment by withoutboats** [comment]
I think the solution is to just use `call_site`

**Comment by withoutboats** [comment]
Went with the call_site solution
